name: Release

on:
  push:
    branches: [main, beta]

jobs:
  changes:
    runs-on: ubuntu-latest
    name: Prepare for publish of any projects with updates
    outputs:      
      auto-pub-poc: ${{ steps.changes.outputs.auto-pub-poc }}
      auto-pub-poc2: ${{ steps.changes.outputs.auto-pub-poc2 }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          auto-pub-poc:
            - 'packages/auto-pub-poc/**'
          auto-pub-poc2:
            - 'packages/auto-pub-poc2/**' 

  auto-pub-poc:
    needs: changes
    if: ${{ needs.changes.outputs.auto-pub-poc == 'true' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        registry-url: 'https://npm.pkg.github.com/'
        scope: '@chargepoint'
    - name: Install dependencies
      run: cd packages/auto-pub-poc && rm -rf node_modules && rm package-lock.json && npm i
    - name: Install semantic-release extra plugins
      run: cd packages/auto-pub-poc && npm install --save-dev @semantic-release/changelog @semantic-release/git      
    - name: Build
      run: cd packages/auto-pub-poc && npm run build      
    - name: Release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.GH_TOKEN }}
      run: cd packages/auto-pub-poc && npx semantic-release

  auto-pub-poc2:
    needs: changes
    if: ${{ needs.changes.outputs.auto-pub-poc2 == 'true' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        registry-url: 'https://npm.pkg.github.com/'
        scope: '@chargepoint'
    - name: Install dependencies
      run: cd packages/auto-pub-poc2 && rm package-lock.json && rm -rf node_modules && npm i
    - name: Install semantic-release extra plugins
      run: cd packages/auto-pub-poc2 && npm install --save-dev @semantic-release/changelog @semantic-release/git      
    - name: Build
      run: cd packages/auto-pub-poc2 && npm run build      
    - name: Release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.GH_TOKEN }}
      run: cd packages/auto-pub-poc2 && npx semantic-release
