name: Release

on:
  push:
    branches: [main, beta]

jobs:
  prepare:
    runs-on: ubuntu-latest
    # Only release if main or beta branch
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta'
    steps:
      - run: echo "${{ github.event.head_commit.message }}"
      - run: echo "${GITHUB_WORKSPACE}"

  # release:
  #   needs: prepare
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3
  #   - name: Setup Node.js
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: 18.x
  #       registry-url: 'https://npm.pkg.github.com/'
  #       scope: '@chargepoint'
  #   - name: Install dependencies
  #     working-directory: ./packages/auto-pub-poc
  #     run: npx ci
  #   - name: Install semantic-release extra plugins
  #     working-directory: ./packages/auto-pub-poc
  #     run: npm install --save-dev @semantic-release/changelog @semantic-release/git      
  #   - name: Build
  #     working-directory: ./packages/auto-pub-poc
  #     run: npm run build      
  #   - name: Release
  #     env:
  #       # GH_TOKEN: ${{ secrets.GH_TOKEN }}
  #       GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  #       NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
  #       # NPM_TOKEN: ${{ secrets.GH_TOKEN }}
  #     working-directory: ./packages/auto-pub-poc
  #     run: npx semantic-release
